### ISSUE TITLE
Minor double-input request bug

### ISSUE THREAD

**Issue by gstarrett2** [filippobottega/ShareFix#1]
Note:  I also posted this on the original thread in the MS forum:
https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/netbios-over-tcpip-broken-since-upgrade-to/fd141dd9-8500-419d-b8e7-ac7255f44ec0

There's a small issue with the app, in that if you choose a numbered interface it will prompt you a second time, and without any prompt text, if you enter a number.  I think I found the problem, see the DIFF below (line 53).

WORKAROUND:  entering the number of the interface again at that 2nd prompt works great.

```
$ git diff
diff --git a/ShareFix/ShareFix/MainModule.vb b/ShareFix/ShareFix/MainModule.vb
index d79ebfd..1a4d77a 100644
--- a/ShareFix/ShareFix/MainModule.vb
+++ b/ShareFix/ShareFix/MainModule.vb
@@ -50,7 +50,7 @@ Module MainModule
         FixInterface(guids(index))
       Next
     ElseIf Integer.TryParse(input, Nothing) Then
-      Dim indexToFix = CInt(Console.ReadLine)
+      Dim indexToFix = CInt(input)^M
       If indexToFix < 0 OrElse indexToFix > subKeyNames.Count - 1 Then
         Console.WriteLine()
         Console.Write($"Index {indexToFix} doesn't exist, press a key to exit")
```

**Comment by filippobottega** [comment]
Thank you for your correction,
  I have just published a new release with your correction.

  Regards,
    Filippo.
