### ISSUE TITLE
Silent switch?

### ISSUE THREAD

**Issue by rom-1** [filippobottega/ShareFix#4]
Thanks for your work! I would love a --silent --all switch for mass deploying in our environment.

**Comment by filippobottega** [comment]
Hello rom-1,
  --silent switch was been implemented in the new version [1.0.3](https://github.com/filippobottega/ShareFix/tree/v1.0.3).

  Regards,
       Filippo.

**Comment by rom-1** [comment]
Great, thanks a lot!
