### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by iCodeSometime** [filippobottega/ShareFix#5]
There is no license on this project, making it very ambiguous whether it is meant to be available for public consumption or not. Technically, any code not explicitly licensed falls under copyright law and is "all rights reserved."

**Comment by iCodeSometime** [comment]
It would be nice if it was clear one way or the other :)

**Comment by filippobottega** [comment]
Hello @kennycoc,
thank you  for your suggestion. 
I have added the MIT License to this repository

Regards,
  Filippo.
